[bar]
order = [ "default" ]

    [bar.default]
    background_opacity = 0.0
    capsule_radius = 4
    capsule_thickness = 0.99999998137354851
    center = [ "group:g1" ]
    end = [ "network", "bluetooth", "volume", "brightness", "battery", "clock", "control-center", "session" ]
    margin_edge = 4
    margin_ends = 0
    padding = 8
    panel_overlap = 0
    radius = 4
    shadow = false
    start = [ "workspaces", "tray", "cpu", "ram" ]
    thickness = 20
    widget_spacing = 4

        [[bar.default.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "media", "audio_visualizer" ]
        opacity = 1.0
        padding = 6.0
        radius = 4.0

[battery]
warning_threshold = 20

[brightness]
minimum_brightness = 0.0099999997764825821

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "notification"

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
auto_hide = true
reserve_space = false

[keybinds]
down = [ "Down", "Ctrl+n" ]
left = [ "Left", "Ctrl+h" ]
right = [ "Right", "Ctrl+l" ]
up = [ "Up", "Ctrl+p" ]
validate = [ "Return", "KP_Enter", "Ctrl+y" ]

[location]
auto_locate = true

[lockscreen]
blur_intensity = 0.59999998658895493
blurred_desktop = true
tint_intensity = 0.39999999105930328

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-widget-0000000000000001" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 768.0
    cy = 749.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 4.0
        input_opacity = 1.0
        input_radius = 4.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 128.0
    box_width = 256.0
    cx = 768.0
    cy = 432.0
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        background_color = "surface"
        background_opacity = 0.80000000000000004
        background_padding = 16
        background_radius = 4
        clock_style = "digital"
        format = "{:%I:%M %p}"
        shadow = false

[nightlight]
enabled = true
temperature_night = 5000

[notification]
offset_x = 4
offset_y = 4
position = "top_left"

[osd]
offset_x = 4
offset_y = 4
position = "top_right"
position_vertical = "bottom_right"

[shell]
corner_radius_scale = 0.30000000447034836

    [shell.animation]
    enabled = false

    [shell.launcher]
    show_icons = false

    [shell.panel]
    control_center_placement = "floating"
    control_center_position = "top_right"
    floating_offset = 4
    open_near_click_control_center = false
    session_placement = "floating"
    shadow = false
    wallpaper_placement = "floating"

[theme]
builtin = "Kanagawa"
community_palette = "Kanagawa Paper"
mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-content"

[wallpaper]
enabled = false

[weather]
effects = false
unit = "imperial"

[widget.audio_visualizer]
bands = 42
color_2 = "tertiary"
mirrored = false
show_when_idle = true
width = 80

[widget.battery]
capsule = true

[widget.brightness]
capsule = true

[widget.clock]
capsule = true
format = "{:%I:%M %p}"

[widget.cpu]
capsule = true

[widget.launcher]
enabled = true

[widget.media]
art_size = 30
capsule = true
hide_album_art = true
hide_when_no_media = true
max_length = 292
title_scroll = "always"

[widget.network]
capsule = true
show_label = false

[widget.ram]
capsule = true

[widget.session]
color = "error"

[widget.spacer_2]
length = 8
type = "spacer"

[widget.sysmon]
capsule = true

[widget.tray]
capsule = true

[widget.volume]
capsule = true

[widget.workspaces]
enabled = true
